// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CartItem struct {
	ID        int32
	CartID    pgtype.UUID
	ProductID int32
	Quantity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Collection struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CollectionImage struct {
	ID           int32
	CollectionID int32
	ImageUrl     string
	CreatedAt    pgtype.Timestamptz
}

type CollectionProduct struct {
	CollectionID int32
	ProductID    int32
	CreatedAt    pgtype.Timestamptz
}

type FitGuide struct {
	ID            int32
	ProductID     int32
	BodyLength    pgtype.Numeric
	SleeveLength  pgtype.Numeric
	ChestWidth    pgtype.Numeric
	ShoulderWidth pgtype.Numeric
	ArmHole       pgtype.Numeric
	FrontRise     pgtype.Numeric
	Inseam        pgtype.Numeric
	Hem           pgtype.Numeric
	BackRise      pgtype.Numeric
	Waist         pgtype.Numeric
	Thigh         pgtype.Numeric
	Knee          pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Product struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProductImage struct {
	ID        int32
	ProductID int32
	ImageUrl  string
	CreatedAt pgtype.Timestamptz
}

type ProductSize struct {
	ID        int32
	ProductID int32
	SizeName  string
	Stock     int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
